//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crepusculum.NINA.SmartPlugControl.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TpLinkUsername {
            get {
                return ((string)(this["TpLinkUsername"]));
            }
            set {
                this["TpLinkUsername"] = value;
            }
        }

        /// <summary>
        /// DPAPI-encrypted (see SecureCredentialStore), never stored in plain text.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TpLinkPasswordProtected {
            get {
                return ((string)(this["TpLinkPasswordProtected"]));
            }
            set {
                this["TpLinkPasswordProtected"] = value;
            }
        }

        /// <summary>0 means no threshold configured. Can be entered directly, or computed from
        /// MaxConsumptionThresholdAmps/PsuEfficiencyPercent - see SmartPlugControl.cs.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxConsumptionThresholdWatts {
            get {
                return ((double)(this["MaxConsumptionThresholdWatts"]));
            }
            set {
                this["MaxConsumptionThresholdWatts"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int PreventiveAlertPercent {
            get {
                return ((int)(this["PreventiveAlertPercent"]));
            }
            set {
                this["PreventiveAlertPercent"] = value;
            }
        }

        /// <summary>0 means this Amps-based calculator isn't in use (Watts was entered directly
        /// instead). Most astro equipment (Pegasus Powerboxes, etc.) is rated in Amps at 12V DC, not
        /// Watts - but a Kasa/Tapo plug only ever measures Watts on the 110V/230V AC side, upstream of
        /// the DC power supply. This lets the user enter the DC-side Amps rating they actually know,
        /// converted to an AC-side Watts threshold via PsuEfficiencyPercent (see
        /// SmartPlugControl.MaxConsumptionThresholdAmps setter for the actual conversion math).</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxConsumptionThresholdAmps {
            get {
                return ((double)(this["MaxConsumptionThresholdAmps"]));
            }
            set {
                this["MaxConsumptionThresholdAmps"] = value;
            }
        }

        /// <summary>Estimated AC-to-DC power supply efficiency (%), since a Kasa/Tapo plug can only
        /// measure AC-side Watts, never the DC-side draw directly. This is always an estimate - the
        /// exact efficiency of a given supply isn't something the plugin can measure.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public int PsuEfficiencyPercent {
            get {
                return ((int)(this["PsuEfficiencyPercent"]));
            }
            set {
                this["PsuEfficiencyPercent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RefreshIntervalSeconds {
            get {
                return ((int)(this["RefreshIntervalSeconds"]));
            }
            set {
                this["RefreshIntervalSeconds"] = value;
            }
        }
    }
}
