//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crepusculum.NINA.SmartPlugControl.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TpLinkUsername {
            get {
                return ((string)(this["TpLinkUsername"]));
            }
            set {
                this["TpLinkUsername"] = value;
            }
        }

        /// <summary>
        /// DPAPI-encrypted (see SecureCredentialStore), never stored in plain text.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TpLinkPasswordProtected {
            get {
                return ((string)(this["TpLinkPasswordProtected"]));
            }
            set {
                this["TpLinkPasswordProtected"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RefreshIntervalSeconds {
            get {
                return ((int)(this["RefreshIntervalSeconds"]));
            }
            set {
                this["RefreshIntervalSeconds"] = value;
            }
        }

        /// <summary>AC line voltage used only to estimate an Amps figure alongside the measured Watts
        /// reading on the equipment page (P = V x I) - purely a display convenience, not used anywhere
        /// in the threshold/alert logic. Default 120V (North America); change for a 230V site.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double LineVoltage {
            get {
                return ((double)(this["LineVoltage"]));
            }
            set {
                this["LineVoltage"] = value;
            }
        }

        /// <summary>Pause after each command sent to an individual outlet of a multi-outlet power strip
        /// (e.g. the Tapo P316M), before moving on to the next outlet in a bulk action - confirmed on
        /// real hardware that switching several outlets back-to-back with no gap could make the whole
        /// strip go unreachable (likely the strip's own WiFi module browning out/restarting under the
        /// combined load of several relays actuating almost simultaneously). Configurable since the
        /// right value depends on the specific hardware/electrical load - default 300ms is a starting
        /// point, not a value verified to be optimal for every model.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int PowerStripCommandDelayMs {
            get {
                return ((int)(this["PowerStripCommandDelayMs"]));
            }
            set {
                this["PowerStripCommandDelayMs"] = value;
            }
        }
    }
}
